repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages:
          - pre-commit
      - id: end-of-file-fixer
        stages:
          - pre-commit
      - id: check-yaml
        stages:
          - pre-commit
      - id: check-added-large-files
        stages:
          - pre-commit

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies: ["@commitlint/config-conventional"]
