repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages:
          - pre-commit
        exclude: ^dist/
      - id: end-of-file-fixer
        stages:
          - pre-commit
        exclude: ^dist/
      - id: check-yaml
        stages:
          - pre-commit
      - id: check-added-large-files
        stages:
          - pre-commit

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        name: lint commit messages
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: check for non-standard formatting concerns
        stages:
          - pre-commit
        additional_dependencies:
          - prettier@3
          - "@trivago/prettier-plugin-sort-imports"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        name: check for linting errors and warnings
        stages:
          - pre-commit
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint-config-prettier
