name: PR Title Linter
description:
  A GitHub Action which lints PR titles using the CommitLint specification
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "activity"
  color: "yellow"
