name: Compile and Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Compile and Commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for the Environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          cache: "npm"

      - name: Install the Dependencies
        run: npm ci --ignore-scripts

      - name: Build the Binary
        run: npm run all

      - name: Commit to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(build): compile the binary using `ncc`"
          commit_options: "--no-verify --signoff"
