name: QA Checks

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  qa-checks:
    name: Run QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for the Environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          cache: "npm"

      - name: Install the Dependencies
        run: npm ci --ignore-scripts

      - name: Run Linting Checks
        run: |
          npm run lint
          npm run format:check

      - name: Build
        run: npm run package
